### ISSUE TITLE
Refactor supervision.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#511]
This started in #506 but for clarity here is a clean ticket. This is a big breaking change.

- [x] Remove all instance methods for supervision.
- [x] Implement a configuration object for actor supervision.
- [x] Add back support for supervision trees ( basics, complete this in `0.17.5` )
- [x] Fix regressions in `Pool`

Also clean up the `supervision` label:

~~#493 null pointer on SupervisionGroup#terminate~~
~~#434 Calling async.run from base class constructor might not be a good design.~~
- [x] celluloid/celluloid-supervision#3 ~~#430~~ supervisors_and_registry.rb not working correctly
- [x] celluloid/celluloid-supervision#4 ~~#355~~ Support for dynamically removing SupervisionGroup members
- [ ] celluloid/celluloid-supervision#5 ~~#331~~ Supervisors attempt to restart the same actor if terminated before restart completes
- [ ] celluloid/celluloid-supervision#6 ~~#233~~ Exception in #initialize took down parent SupervisionGroup

**Comment by e2** [comment]
:+1

**Comment by digitalextremist** [comment]
Refactor as gem, per #562.

**Comment by Senjai** [comment]
@digitalextremist :+1: Sorry I wasn't able to follow through on the original issue, work caught up with me. I will keep watch though! I dont know why there's so much talk about extracting things into seperate gems. I don't know where the benefit is unless they can be run on their own. I'm all for removing as much knowledge from the system as possible though.

**Comment by tarcieri** [comment]
@Senjai moving thing out of core allows us to focus more on the stability of core, while accepting and informing people of different levels of stability for the gems.

It also allows us to stabilize the API of core (for e.g. a Celluloid 1.0 release) while leaving the unstable parts to mature separately in gems.

**Comment by Senjai** [comment]
@tarcieri that makes sense, so they would take more of a plug-in role?

**Comment by tarcieri** [comment]
Yes. It also allows for parallel development of replacements (e.g. `celluloid-coordinator` should replace `celluloid-pool`). If these features are gems and not core functionality, I think people might be more interested in evaluating alternatives.

**Comment by digitalextremist** [comment]
The sub-issues in this are all going to be moved to the issue tracker in their own gem and closed here, but this will remain for overall status.

**Comment by digitalextremist** [comment]
Now, we all know the benchmarks on CI are prone to outside fluctuation and mean basically nothing for performance testing, only emergency detection. But..

### `ruby-2.2.0`

Before major refactoring push:

```
Top 3 slowest examples (0.33188 seconds, 67.1% of total time):
  Celluloid::Supervisor registers actors and reregisters them when they die
    0.11429 seconds ./spec/celluloid/supervisor_spec.rb:40
  Celluloid::Supervisor restarts actors when they die
    0.11223 seconds ./spec/celluloid/supervisor_spec.rb:21
  Celluloid::Supervisor creates supervisors via Actor.supervise
    0.10535 seconds ./spec/celluloid/supervisor_spec.rb:59
Top 2 slowest example groups:
  Celluloid::Supervisor
    0.08875 seconds average (0.44376 seconds / 5 examples) ./spec/celluloid/supervisor_spec.rb:1
  Celluloid::SupervisionGroup
    0.0082 seconds average (0.04922 seconds / 6 examples) ./spec/celluloid/supervision_group_spec.rb:1
```
Finished in **0.49479** seconds (files took 0.54699 seconds to load)

---

After major refactoring push:
```
Top 3 slowest examples (0.32998 seconds, 85.1% of total time):
  Celluloid::Supervisor registers actors and reregisters them when they die
    0.11331 seconds ./spec/celluloid/supervision/supervisor_spec.rb:40
  Celluloid::Supervisor creates supervisors via Actor.supervise
    0.10882 seconds ./spec/celluloid/supervision/supervisor_spec.rb:59
  Celluloid::Supervisor restarts actors when they die
    0.10786 seconds ./spec/celluloid/supervision/supervisor_spec.rb:21
Top 2 slowest example groups:
  Celluloid::Supervisor
    0.08374 seconds average (0.33498 seconds / 4 examples) ./spec/celluloid/supervision/supervisor_spec.rb:1
  Celluloid::Supervision::Group
    0.00545 seconds average (0.03273 seconds / 6 examples) ./spec/celluloid/supervision/group_spec.rb:1
```
Finished in **0.39854** seconds (files took 0.56842 seconds to load)

---

### `jruby-1.7.19`

Before:
```
Top 3 slowest examples (1.01 seconds, 44.1% of total time):
  Celluloid::Supervisor creates supervisors and registers actors via Actor.supervise_as
    0.543 seconds ./spec/celluloid/supervisor_spec.rb:75
  Celluloid::Supervisor restarts actors when they die
    0.237 seconds ./spec/celluloid/supervisor_spec.rb:21
  Celluloid::SupervisionGroup when supervising a single actor runs applications
    0.225 seconds ./spec/celluloid/supervision_group_spec.rb:64
Top 2 slowest example groups:
  Celluloid::Supervisor
    0.2554 seconds average (1.28 seconds / 5 examples) ./spec/celluloid/supervisor_spec.rb:1
  Celluloid::SupervisionGroup
    0.16333 seconds average (0.98 seconds / 6 examples) ./spec/celluloid/supervision_group_spec.rb:1
```
Finished in **2.28** seconds (files took 5.36 seconds to load)

---

After:
```
Top 3 slowest examples (0.927 seconds, 54.6% of total time):
  Celluloid::Supervision::Group when supervising a single actor allows external access to the internal registry
    0.408 seconds ./spec/celluloid/supervision/group_spec.rb:81
  Celluloid::Supervisor registers actors and reregisters them when they die
    0.272 seconds ./spec/celluloid/supervision/supervisor_spec.rb:40
  Celluloid::Supervisor restarts actors when they die
    0.247 seconds ./spec/celluloid/supervision/supervisor_spec.rb:21
Top 2 slowest example groups:
  Celluloid::Supervisor
    0.2155 seconds average (0.862 seconds / 4 examples) ./spec/celluloid/supervision/supervisor_spec.rb:1
  Celluloid::Supervision::Group
    0.13667 seconds average (0.82 seconds / 6 examples) ./spec/celluloid/supervision/group_spec.rb:1
```
Finished in **1.7** seconds (files took 3.75 seconds to load)

**Comment by digitalextremist** [comment]
Not finding anything really glaring on the level of needing to "remove instance methods" at the moment, other than the methods that preload `Supervision::Containers` with blocks to run at start of the supervisor ( previously `SupervisionGroup` )

**Comment by digitalextremist** [comment]
Or else, what I've refactored it to be seems to be safe so far.

**Comment by digitalextremist** [comment]
This is substantially finished, with the remaining afterthoughts lingering, possibly not happening this release, so this ticket will be closed and anything remaining will be continued in the appropriate gem.
