### ISSUE TITLE
Test overhaul.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#526]
This involves the following, but is broader than these:
- [x] #524 Deal with `:flaky` tests.
- [x] #525 Get travis working on `jruby-head`
- [x] #528 Radical amount of warnings in specs [ @e2 in #530 ]
- [x] Eradicate timeouts on all RVMs.

In general, we need to refactor how tests are handled, removing intermittence; not disabling tests but removing the flaky factor -- which seems largely about putting in some strategically placed `sleep` calls and removing reuse of threads and fibers.

While we don't need to go so far as to remove `allowed failures` per se, it would be nice to be able to detect defects in bleeding-edge RVM's with Celluloid, rather than coming to expect failures.

**Comment by digitalextremist** [comment]
@e2 are you willing to team up on this?

**Comment by e2** [comment]
I can't make any promises. I think I'll start a new Celluloid branch, because debugging tougher issues may need lots of codebase changes (and so, PRs won't make sense) - and I'll "backport" changes to `master` on a case-by-case basis. I'll probably need to IRC for this quite a bit...

I recommend merging in any pending PRs first - because I'll likely have to reorganize/customize things in the codebase and logic to debug/work/fix faster.

**Comment by e2** [comment]
@tarcieri - what's the "official status" behind ThreadTask vs FiberTask? I have the impression that ThreadTask provides backtraces, but is slower/more flaky - while FiberTask over works well, though doesn't provide as much useful debugging info (and I don't know about JRuby). Not to mention that Fibers are really threads on JRuby anyway (along with all the other consequences).

**Comment by digitalextremist** [comment]
Sounds good. I'm trying to clear out at least everything in the `0.16.5` milestone, and I'm picking off several `0.17.0` issues also. By the way... this `Probe on boot should capture system actor spawn` failure happening in `2.0.0` is a carry-over from `$CELLULOID_MONITORING`

**Comment by digitalextremist** [comment]
@e2 there is a patch out providing backtraces on `TaskFiber` -- I'm thinking we should really merge that.

**Comment by digitalextremist** [comment]
I think this `Probe on boot should capture system actor spawn` failure is `:flaky` but I'm getting mixed results.

**Comment by e2** [comment]
@digitalextremist - probably worth checking out/cleaning up the project branches too. future-cancel sounds cool...

**Comment by tarcieri** [comment]
@e2 both are supported. TaskFiber is definitely more stable. @mperham was trying out TaskThreads in Sidekiq.

**Comment by digitalextremist** [comment]
As mentioned in #535, please call for pulls into the `refactor-test-suite` branch so we can have a few of us go through and review all these changes all at once, as this is a pretty high-traffic set of revisions.

**Comment by digitalextremist** [comment]
@dilumnavanjana if you want to help review #535 as part of your `GSoC` orientation leading up to possibly taking on #509, check out the `refactor-test-suite` branch in your fork and ask questions in your own repository. Enable "Issues" on your fork and @ me there to discuss individual questions there.

**Comment by digitalextremist** [comment]
In dealing with `:flaky` tests, it seems that the issue is killing Threads between tests, which under jRuby means killing Fibers also, which causes a total melt down. But then when you avoid the meltdown, the tests start failing intermittently, because now there are undead Threads/Fibers wandering around.

**Comment by digitalextremist** [comment]
This seems like one of the key issues blocking #547

**Comment by digitalextremist** [comment]
@e2 this and #524 seem basically shored up, except for `jruby-head`; confirm?

**Comment by e2** [comment]
@digitalextremist - not yet. There are a lot of (possibly breaking) changes due to the "improved" InternalPool (now Groups::Pool). These may need minor or not-as-minor changes to the tests and may introduce and/or bring up flaky tests. Also, some tests may still be failing. Maybe once the `:flaky` flag is removed everywhere and tests are green, we could close this.

Still too early.

**Comment by digitalextremist** [comment]
All `:flaky` markers have been purged, ready to remove all evidence of that, per end of #524. And I would not think any issues with `Group::Pool` count to the point of keeping this open. That can be relegated to #568

**Comment by digitalextremist** [comment]
@e2 extremely good work on your end. I know there is more to do, but we reached 100% green for all rubies.
