### ISSUE TITLE
0.18.0 release tracking issue

### ISSUE THREAD

**Issue by tarcieri** [celluloid/celluloid#789]
This is a tracking issue for a Celluloid 0.18 release (see also #762, #728).

The [master branch](https://github.com/celluloid/celluloid/tree/master) contains the code to be released. This includes a lot of refactoring to consolidate Celluloid from fragmented gems and removed global variables and other hard-to-maintain bits.

I don't have time to do the release myself though (see #779), so I'm looking for volunteers to address the following items below:

- [x] Timeout extensions (#491) - decide whether to merge this PR or abandon it (EDIT: abandoning the PR)
- [x] [CHANGES.md](https://github.com/celluloid/celluloid/blob/master/CHANGES.md) - add v0.18.0 release notes.
- [ ] Manual testing of the upgrade against some real-world Celluloid applications: it's been a *long* time since Celluloid had a release like this, and there's a good chance there are some unaddressed bugs not caught by automated tests.

If you are interested in working on either of these items, or would like to suggest additional items which should make it into a v0.18.0 release, please respond below.

**Comment by tarcieri** [comment]
I mean trying out the 0.18.0.pre2 prerelease in some real-world Celluloid projects and seeing if there are issues with the upgrade before we do a release.

**Comment by dilumn** [comment]
@tarcieri I created the release note for `v0.18.0` here https://github.com/celluloid/celluloid/pull/809

Usage of `0.18.0.pre2` is not huge compare to other releases. So what do you think about we release `0.18.0` now & address any bugs as soon as possible(if there are any)?

**Comment by tarcieri** [comment]
@dilumn sounds good. Give me your RubyGems handle and I can add you as an owner

**Comment by dilumn** [comment]
It is https://rubygems.org/profiles/dilumn

**Comment by tarcieri** [comment]
Invite sent

**Comment by dilumn** [comment]
Celluloid `0.18.0` released

https://github.com/celluloid/celluloid/releases/tag/v0.18.0

Closing this ticket
